name: Bug Report
description: Report an Issue or Bug with the Package
title: "[Bug]: "
labels: ["bug"]
body:
    - type: markdown
      attributes:
          value: |
              We're sorry to hear you have a problem. Can you help us solve it by providing the following details.
    - type: textarea
      id: what-happened
      attributes:
          label: What happened?
          description: Please explain what you expect to happen and what did happen instead.
          placeholder: Please explain what you expect to happen and what did happen instead.
      validations:
          required: true
    - type: textarea
      id: how-to-reproduce
      attributes:
          label: How to reproduce the bug?
          description: How did this occur, provide a set of reliable steps if possible.
          placeholder: How did this occur, provide a set of reliable steps if possible.
      validations:
          required: true
    - type: input
      id: package-version
      attributes:
          label: Package Version
          placeholder: 1.0.0
      validations:
          required: true
    - type: input
      id: php-version
      attributes:
          label: PHP Version
          placeholder: 8.4.0
      validations:
          required: true
    - type: input
      id: laravel-version
      attributes:
        label: Laravel Version
        placeholder: 12.0.0
      validations:
        required: true
    - type: input
      id: databse-driver
      attributes:
        label: Database Driver
        placeholder: mysql
      validations:
        required: true
