name: tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    timeout-minutes: 5

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: query_builder_criteria_testing
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        ports:
          - 3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    strategy:
      fail-fast: true
      matrix:
        php: [8.4, 8.3, 8.2]
        dependency-version: [prefer-stable]

    name: PHP:${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, mbstring, zip, mbstring, pdo, sqlite, pdo_sqlite
          coverage: pcov

      - name: Install dependencies
        run:  composer install --no-interaction --prefer-dist --no-scripts

      - name: Execute tests
        run: ./vendor/bin/phpunit
